/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ghost
 */
public class Lib extends javax.swing.JFrame {
Connection conexion;
    /**
     * Creates new form Lib
     */
    public Lib() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        nomdre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        año = new javax.swing.JTextField();
        tipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tema = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        prestamos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        reparaciones = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        libro = new javax.swing.JButton();
        presta = new javax.swing.JButton();
        limpiar8 = new javax.swing.JButton();
        consulta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 0, 358, 294));
        getContentPane().add(nomdre, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 0, 87, -1));

        jLabel8.setText("Nombre");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, -1, -1));

        jLabel2.setText("Autor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 29, -1, -1));

        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });
        getContentPane().add(autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 26, 87, -1));

        jLabel1.setText("Tipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, -1, -1));

        jLabel3.setText("Fecha de Publicacion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, -1, -1));
        getContentPane().add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 78, 87, -1));

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "inicio" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 52, 87, -1));

        jLabel6.setText("Prestamos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 55, -1, -1));
        getContentPane().add(tema, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 78, 87, -1));

        jLabel7.setText("Tema");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 81, -1, -1));
        getContentPane().add(prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 52, 87, -1));

        jLabel5.setText("Mantenimientos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 29, -1, -1));
        getContentPane().add(reparaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 26, 87, -1));

        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 0, 87, -1));

        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 3, -1, -1));

        libro.setText("Agregar un Libro");
        libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libroActionPerformed(evt);
            }
        });
        getContentPane().add(libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 104, 141, -1));

        presta.setText("Registrar un Prestamo");
        presta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestaActionPerformed(evt);
            }
        });
        getContentPane().add(presta, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 133, 141, -1));

        limpiar8.setText("Limpiar Tabla");
        limpiar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar8ActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 191, 141, -1));

        consulta.setText("Consultar Libros");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        getContentPane().add(consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 162, 141, -1));

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 220, 141, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel9.setText("Registro de Libros");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 254, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro Libros.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 680, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked
        // TODO add your handling code here:
        nomdre.setText(tabla1.getValueAt(tabla1.getSelectedRow(),0).toString());
        autor.setText(tabla1.getValueAt(tabla1.getSelectedRow(),1).toString());
        año.setText(tabla1.getValueAt(tabla1.getSelectedRow(),2).toString());
        fecha.setText(tabla1.getValueAt(tabla1.getSelectedRow(),3).toString());
        reparaciones.setText(tabla1.getValueAt(tabla1.getSelectedRow(),4).toString());
        prestamos.setText(tabla1.getValueAt(tabla1.getSelectedRow(),5).toString());
        tema.setText(tabla1.getValueAt(tabla1.getSelectedRow(),6).toString());
    }//GEN-LAST:event_tabla1MouseClicked

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conexion = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Biblioteca;integratedSecurity=true;");
            System.out.println("conectado");
            Statement stmt = conexion.createStatement();
            stmt.executeQuery("select*from tiposlibro");
            ResultSet rs= stmt.getResultSet();
            if(rs!=null)
            {
                while(rs.next())
                {
                    tipo.addItem(rs.getString(1));

                }
            }
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Error");
        }

    }//GEN-LAST:event_tipoActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libroActionPerformed
        // TODO add your handling code here:
        String instruccion;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conexion = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Biblioteca;integratedSecurity=true;");
            JOptionPane.showMessageDialog(null, "Conectado");

            instruccion = "{call ingresarLi(?,?,?,?,?,?,?,?)}";
            PreparedStatement s = conexion.prepareStatement(instruccion);
            s.setString(1, nomdre.getText());
            s.setString(2, autor.getText());
            s.setString(3,(String) tipo.getSelectedItem());
            s.setString(4, año.getText());
            s.setString(5, fecha.getText());
            s.setString(6, reparaciones.getText());
            s.setString(7, prestamos.getText());
            s.setString(8, tema.getText());

            s.executeUpdate();

            JOptionPane.showMessageDialog(null, "Se añadio un libro");
            nomdre.setText("");
            autor.setText("");
            tipo.setSelectedItem("");
            año.setText("");
            fecha.setText("");
            reparaciones.setText("");
            prestamos.setText("");
            tema.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
    }//GEN-LAST:event_libroActionPerformed

    private void prestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestaActionPerformed
        // TODO add your handling code here:
        String instruccion;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conexion = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Biblioteca;integratedSecurity=true;");
            JOptionPane.showMessageDialog(null, "Conectado");

            instruccion = "{call modificarLi(?,?,?,?,?,?,?,?)}";
            PreparedStatement s = conexion.prepareStatement(instruccion);
            s.setString(1, nomdre.getText());
            s.setString(2, autor.getText());
            s.setString(3,(String) tipo.getSelectedItem());
            s.setString(4, año.getText());
            s.setString(5, fecha.getText());
            s.setString(6, reparaciones.getText());
            s.setString(7, prestamos.getText());
            s.setString(8, tema.getText());

            s.executeUpdate();

            JOptionPane.showMessageDialog(null, "Se añadio un prestamo");
            nomdre.setText("");
            autor.setText("");
            tipo.setSelectedItem("");
            año.setText("");
            fecha.setText("");
            reparaciones.setText("");
            prestamos.setText("");
            tema.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
    }//GEN-LAST:event_prestaActionPerformed

    private void limpiar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar8ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabla2 = (DefaultTableModel) tabla1.getModel();
        for(int i=0;i<tabla2.getRowCount();i++){
            tabla2.removeRow(i);
            tabla2.setColumnCount(0);
        }
    }//GEN-LAST:event_limpiar8ActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabla = (DefaultTableModel) tabla1.getModel();
        tabla.addColumn("Nombre");
        tabla.addColumn("Autor");
        tabla.addColumn("Tipo");
        tabla.addColumn("Fecha de Publicaciòn");
        tabla.addColumn("Fecha de Registro");
        tabla.addColumn("Reparaciones");
        tabla.addColumn("Numero de Prestamos");
        tabla.addColumn("Motivo");

        String instruccion = "select*from libro";
        tabla.setRowCount(0);
        try {
            System.out.println("Conectado");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conexion = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Biblioteca;integratedSecurity=true;");
            Statement stmt = conexion.createStatement();
            stmt.executeQuery(instruccion);
            ResultSet rs = stmt.getResultSet();
            if (rs != null) {
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    v.add(rs.getString(4));
                    v.add(rs.getString(5));
                    v.add(rs.getString(6));
                    v.add(rs.getString(7));
                    v.add(rs.getString(8));

                    tabla.addRow(v);
                }
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_consultaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuSeleccion M =new MenuSeleccion();
        M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lib().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autor;
    private javax.swing.JTextField año;
    private javax.swing.JButton consulta;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton libro;
    private javax.swing.JButton limpiar8;
    private javax.swing.JTextField nomdre;
    private javax.swing.JButton presta;
    private javax.swing.JTextField prestamos;
    private javax.swing.JTextField reparaciones;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField tema;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
