/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ghost
 */
public class Prestado extends javax.swing.JFrame {
Connection conexion;
    /**
     * Creates new form Prestado
     */
    public Prestado() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        nomdreU = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        especial2 = new javax.swing.JButton();
        especial = new javax.swing.JButton();
        consulta = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        libros = new javax.swing.JButton();
        Fecha = new javax.swing.JTextField();
        fecha = new javax.swing.JLabel();
        libro = new javax.swing.JLabel();
        Libro = new javax.swing.JTextField();
        tipo = new javax.swing.JLabel();
        Tipo = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();
        Estado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        limpiar8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 0, -1, -1));

        nomdreU.setForeground(new java.awt.Color(0, 204, 204));
        nomdreU.setText("Usuario");
        getContentPane().add(nomdreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1, 98, 19));

        agregar.setText("Registrar Prestamo");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, -1));

        especial2.setText("Prestamos Vencidos");
        especial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especial2ActionPerformed(evt);
            }
        });
        getContentPane().add(especial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 113, -1, -1));

        especial.setText("Prestamos Vigentes");
        especial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialActionPerformed(evt);
            }
        });
        getContentPane().add(especial, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 113, -1, -1));

        consulta.setText("Mostrar Prestamos");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        getContentPane().add(consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 84, -1, -1));

        eliminar.setText("Eliminar una Reservacion");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 84, -1, -1));

        libros.setText("Consultar Libros");
        libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosActionPerformed(evt);
            }
        });
        getContentPane().add(libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 29, 80, -1));

        fecha.setForeground(new java.awt.Color(0, 204, 204));
        fecha.setText("Fecha de Prestamo");
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));

        libro.setForeground(new java.awt.Color(0, 204, 204));
        libro.setText("Libro");
        getContentPane().add(libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 4, -1, -1));
        getContentPane().add(Libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 1, 104, -1));

        tipo.setForeground(new java.awt.Color(0, 204, 204));
        tipo.setText("Tipo");
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, -1));
        getContentPane().add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 56, 92, -1));

        estado.setForeground(new java.awt.Color(0, 204, 204));
        estado.setText("Estado");
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 59, -1, -1));

        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });
        getContentPane().add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 56, 117, -1));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 154, 406, 222));

        limpiar8.setText("Limpiar Tabla");
        limpiar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar8ActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 55, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Registro de Prestamos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 29, 174, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro Prestamos.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuSeleccion M =new MenuSeleccion();
        M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        String instruccion;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conexion = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Biblioteca;integratedSecurity=true;");
            JOptionPane.showMessageDialog(null, "Conectado");

            instruccion = "{call ingresarP(?,?,?,?,?)}";
            PreparedStatement s = conexion.prepareStatement(instruccion);
            s.setString(1, usuario.getText());
            s.setString(2, Fecha.getText());
            s.setString(3, Libro.getText());
            s.setString(4, Tipo.getText());
            s.setString(5, Estado.getText());

            s.executeUpdate();

            JOptionPane.showMessageDialog(null, "Se añadio un Prestamo");
            usuario.setText("");
            Fecha.setText("");
            Libro.setText("");
            Tipo.setText("");
            Estado.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void especial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especial2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabla = (DefaultTableModel) tabla1.getModel();
        tabla.addColumn("ID");
        tabla.addColumn("Nombre");
        tabla.addColumn("Fecha");
        tabla.addColumn("Libro");
        tabla.addColumn("Tipo");
        tabla.addColumn("Estado");

        String instruccion = "select*from prestamos where estado='vencido'";
        tabla.setRowCount(0);
        try {
            System.out.println("Conectado");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conexion = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Biblioteca;integratedSecurity=true;");
            Statement stmt = conexion.createStatement();
            stmt.executeQuery(instruccion);
            ResultSet rs = stmt.getResultSet();
            if (rs != null) {
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    v.add(rs.getString(4));
                    v.add(rs.getString(5));
                    v.add(rs.getString(6));

                    tabla.addRow(v);
                }
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_especial2ActionPerformed

    private void especialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabla = (DefaultTableModel) tabla1.getModel();
        tabla.addColumn("ID");
        tabla.addColumn("Nomnre");
        tabla.addColumn("Fecha");
        tabla.addColumn("Libro");
        tabla.addColumn("Tipo");
        tabla.addColumn("Estado");

        String instruccion = "select*from prestamos where estado='vigente'";
        tabla.setRowCount(0);
        try {
            System.out.println("Conectado");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conexion = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Biblioteca;integratedSecurity=true;");
            Statement stmt = conexion.createStatement();
            stmt.executeQuery(instruccion);
            ResultSet rs = stmt.getResultSet();
            if (rs != null) {
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    v.add(rs.getString(4));
                    v.add(rs.getString(5));
                    v.add(rs.getString(6));

                    tabla.addRow(v);
                }
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_especialActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabla = (DefaultTableModel) tabla1.getModel();
        tabla.addColumn("ID");
        tabla.addColumn("Usuario");
        tabla.addColumn("Fecha");
        tabla.addColumn("Libro");
        tabla.addColumn("Tipo");
        tabla.addColumn("Estado");

        String instruccion = "select*from prestamos";
        tabla.setRowCount(0);
        try {
            System.out.println("Conectado");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conexion = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Biblioteca;integratedSecurity=true;");
            Statement stmt = conexion.createStatement();
            stmt.executeQuery(instruccion);
            ResultSet rs = stmt.getResultSet();
            if (rs != null) {
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    v.add(rs.getString(4));
                    v.add(rs.getString(5));
                    v.add(rs.getString(6));

                    tabla.addRow(v);
                }
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_consultaActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        String instruccion;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conexion = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Biblioteca;integratedSecurity=true;");
            JOptionPane.showMessageDialog(null, "Conectado");

            instruccion = "{call eliminarP(?,?)}";
            PreparedStatement s = conexion.prepareStatement(instruccion);
            s.setString(1, usuario.getText());
            s.setString(2, Estado.getText());

            s.executeUpdate();

            JOptionPane.showMessageDialog(null, "Se añadio un prestamo");
            usuario.setText("");
            Estado.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabla = (DefaultTableModel) tabla1.getModel();
        tabla.addColumn("Nombre");
        tabla.addColumn("Autor");
        tabla.addColumn("Tipo");
        tabla.addColumn("Fecha de Publicaciòn");
        tabla.addColumn("Fecha de Registro");
        tabla.addColumn("Reparaciones");
        tabla.addColumn("Prestamos");
        tabla.addColumn("Tema");

        String instruccion = "select*from libro";
        tabla.setRowCount(0);
        try {
            System.out.println("Conectado");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conexion = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Biblioteca;integratedSecurity=true;");
            Statement stmt = conexion.createStatement();
            stmt.executeQuery(instruccion);
            ResultSet rs = stmt.getResultSet();
            if (rs != null) {
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    v.add(rs.getString(4));
                    v.add(rs.getString(5));
                    v.add(rs.getString(6));
                    v.add(rs.getString(7));
                    v.add(rs.getString(8));

                    tabla.addRow(v);
                }
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_librosActionPerformed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoActionPerformed

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked
        // TODO add your handling code here:
        usuario.setText(tabla1.getValueAt(tabla1.getSelectedRow(),1).toString());
        Fecha.setText(tabla1.getValueAt(tabla1.getSelectedRow(),2).toString());
        Libro.setText(tabla1.getValueAt(tabla1.getSelectedRow(),3).toString());
        Tipo.setText(tabla1.getValueAt(tabla1.getSelectedRow(),4).toString());
        Estado.setText(tabla1.getValueAt(tabla1.getSelectedRow(),5).toString());

    }//GEN-LAST:event_tabla1MouseClicked

    private void limpiar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar8ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabla2 = (DefaultTableModel) tabla1.getModel();
        for(int i=0;i<tabla2.getRowCount();i++){
            tabla2.removeRow(i);
            tabla2.setColumnCount(0);
        }
    }//GEN-LAST:event_limpiar8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Estado;
    private javax.swing.JTextField Fecha;
    private javax.swing.JTextField Libro;
    private javax.swing.JTextField Tipo;
    private javax.swing.JButton agregar;
    private javax.swing.JButton consulta;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton especial;
    private javax.swing.JButton especial2;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel libro;
    private javax.swing.JButton libros;
    private javax.swing.JButton limpiar8;
    private javax.swing.JLabel nomdreU;
    private javax.swing.JTable tabla1;
    private javax.swing.JLabel tipo;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
